### ISSUE TITLE
Can't build vio

### ISSUE THREAD

**Issue by chc4** [alpha123/vio#1]
Attempting to run `make` outputs

> make: **\* No rule to make target 'vecapply.c', needed by 'all'.  Stop.

That file doesn't seem to exist, however. Removing vecapply.c from the makefile has math.c complain about cblas.h, since under Arch Linux the path to the header file is /usr/include/cblas.h, not /usr/include/blas/cblas.h

Fixing the header include makes stdvio.c error, because it's including vecapply.h, which also doesn't exist. Removing that include gives errors about `vio_fold` and `vio_partition` in stdvio.c, but according to grep and [GitHub search](https://github.com/alpha123/vio/search?utf8=%E2%9C%93&q=vio_fold) that's never defined anywhere.

I assume it's just a missing git add for vecapply, but not sure how to fix the blas include without makefile hackery.

**Comment by chc4** [comment]
https://github.com/alpha123/vio/commit/42a543b66d015ed091c93dcf1faeceada1b92df9 fixes the vecapply stuff, but still has Makefile issues. Had to patch math.c to `#include <cblas.h>` and Makefile to `BLAS_IMPL=cblas`.

**Comment by alpha123** [comment]
I actually develop Vio with [fossil](http://fossil-scm.org/) and periodically mirror it here, which is probably how I managed to forget vecapply. :( Sorry!

As for the second error, do you have OpenBLAS installed? If so, what OS are you on? I've only compiled under Cygwin and FreeBSD, both of which put the BLAS header in blas/cblas.h.

**Comment by chc4** [comment]
I'm using Arch Linux, which doesn't have an OpenBLAS package. Instead it has `cblas`.
