### ISSUE TITLE
Memory corruption with /+

### ISSUE THREAD

**Issue by chc4** [alpha123/vio#4]
```
vio> {1 2 3} {1 2 3} /+
Error: Fatal: unable to allocate memory.

empty stack
vio> a
[1]    9085 segmentation fault (core dumped)  ./vio
```

or, alternatively:

```
vio> a
Error: Attempted to call undefined word.
Attempted to call 'a', but that word is not defined.

Perhaps it was a typo, and you meant one of the following:
- s
- d
- ,
empty stack
vio> /+
*** Error in `./vio': free(): invalid pointer: 0x00007fa1d9e43b61 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x72055)[0x7fa1d9b17055]
/usr/lib/libc.so.6(+0x779a6)[0x7fa1d9b1c9a6]
/usr/lib/libc.so.6(+0x7818e)[0x7fa1d9b1d18e]
./vio[0x4119c3]
./vio[0x411a10]
./vio[0x408532]
./vio[0x40b5b8]
./vio[0x40bed8]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fa1d9ac5610]
./vio[0x404209]
======= Memory map: ========
[snip]
```

**Comment by alpha123** [comment]
First issue is that /+ is actually a syntax error (folding over + is \+), but was getting incorrectly reported as a failure to allocate.

Second issue was a bit weirder. malloc & calloc occasionally seem to try to align something on a bad boundary. Are you on a 32-bit or 64-bit OS and are you running a 32-bit or 64-bit compile (GCC defaults to 64-bit usually, though I suppose that's distro-dependent).

**Comment by alpha123** [comment]
While this particular issue was fixed, something similar involving calling undefined words still pops up (but is a bit less obvious of a fix). See #5.
